// Auto-generated by Strada Module Initializer Generator
// Do not modify this file manually

using System;
using System.Collections.Generic;
using Strada.Core.Modules;
using Strada.Core.DI;

namespace Strada.Generated
{
    public static class GeneratedModuleInitializer
    {
        public static readonly Type[] ModuleTypes = new Type[]
        {
            typeof(Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.LowPriorityModule),
            typeof(Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.TestModuleA),
            typeof(Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.TestModuleB),
            typeof(Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.DependentModule),
            typeof(Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.ChainedDependentModule),
            typeof(Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.CircularModuleA),
            typeof(Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.CircularModuleB),
            typeof(Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.HighPriorityModule),
        };

        public static void RegisterAll(ModuleRegistry registry)
        {
            registry.RegisterModule(new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.LowPriorityModule(), -10);
            registry.RegisterModule(new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.TestModuleA(), 0);
            registry.RegisterModule(new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.TestModuleB(), 0);
            registry.RegisterModule(new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.DependentModule(), 0);
            registry.RegisterModule(new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.ChainedDependentModule(), 0);
            registry.RegisterModule(new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.CircularModuleA(), 0);
            registry.RegisterModule(new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.CircularModuleB(), 0);
            registry.RegisterModule(new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.HighPriorityModule(), 10);
        }

        public static List<IModuleInstaller> CreateAll()
        {
            return new List<IModuleInstaller>
            {
                new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.LowPriorityModule(),
                new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.TestModuleA(),
                new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.TestModuleB(),
                new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.DependentModule(),
                new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.ChainedDependentModule(),
                new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.CircularModuleA(),
                new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.CircularModuleB(),
                new Strada.Core.Tests.Tests.Runtime.Modules.ModuleRegistryTests.HighPriorityModule(),
            };
        }
    }
}
