// Auto-generated by Strada Module Registry Generator
// Do not modify this file manually

using System.Collections.Generic;
using Strada.Core.Modules;
using UnityEngine;

namespace Strada.Generated
{
    /// <summary>
    /// Registry of all ModuleConfig assets found in the project.
    /// Use this for validation, discovery, and debugging purposes.
    /// </summary>
    public static class GeneratedModuleRegistry
    {
        /// <summary>
        /// Information about a discovered module.
        /// </summary>
        public readonly struct ModuleInfo
        {
            public readonly string GUID;
            public readonly string AssetPath;
            public readonly string ModuleName;
            public readonly string TypeName;
            public readonly int Priority;

            public ModuleInfo(string guid, string assetPath, string moduleName, string typeName, int priority)
            {
                GUID = guid;
                AssetPath = assetPath;
                ModuleName = moduleName;
                TypeName = typeName;
                Priority = priority;
            }
        }

        /// <summary>
        /// All discovered module configurations at generation time.
        /// </summary>
        public static readonly ModuleInfo[] DiscoveredModules = new ModuleInfo[]
        {
            new ModuleInfo(
                "1c9cd60d03fed4335ae6efa3751cfe91",
                "Assets/Modules/BoardDefenceModule/Resources/Configs/BoardDefenceModuleConfig.asset",
                "BoardDefence",
                "BoardDefence.BoardDefenceModuleConfig",
                0),
            new ModuleInfo(
                "0a3f3af89e97a455eb5541cbe9820909",
                "Packages/com.strada.modules/ScreenModule/Assets/Resources/Screen/ScreenModuleConfig.asset",
                "Screen",
                "Strada.Modules.Screen.ScreenModuleConfig",
                50),
            new ModuleInfo(
                "cc5d7a3b05d604505a322bba8a0ea544",
                "Assets/Modules/BoardDefenceModule/Resources/Configs/BoardUIModuleConfig.asset",
                "BoardUI",
                "BoardDefence.UI.BoardUIModuleConfig",
                60),
        };

#if UNITY_EDITOR
        /// <summary>
        /// Loads all discovered ModuleConfig assets from the AssetDatabase.
        /// Editor-only: Use for validation and tooling.
        /// </summary>
        public static List<ModuleConfig> LoadAllFromAssetDatabase()
        {
            var result = new List<ModuleConfig>();
            foreach (var info in DiscoveredModules)
            {
                var config = UnityEditor.AssetDatabase.LoadAssetAtPath<ModuleConfig>(info.AssetPath);
                if (config != null)
                    result.Add(config);
            }
            return result;
        }

        /// <summary>
        /// Validates that all discovered modules still exist and are properly configured.
        /// Returns a list of validation issues, if any.
        /// </summary>
        public static List<string> ValidateModules()
        {
            var issues = new List<string>();
            foreach (var info in DiscoveredModules)
            {
                var config = UnityEditor.AssetDatabase.LoadAssetAtPath<ModuleConfig>(info.AssetPath);
                if (config == null)
                {
                    issues.Add($"Module '{info.ModuleName}' not found at path: {info.AssetPath}");
                    continue;
                }
                if (config.GetType().FullName != info.TypeName)
                {
                    issues.Add($"Module '{info.ModuleName}' type changed from {info.TypeName} to {config.GetType().FullName}");
                }
            }
            return issues;
        }
#endif
    }
}
